<html>


<head> 
<title> xkde </title>

<script type="text/javascript" src="jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="jquery.hoverIntent.js"></script>


<script language="JavaScript">
<!--

function newImage( imgSrc ) {
 var imgName = new Image();
 imgName.src = imgSrc;
 return imgName;
}

function change( imgName, imgLocation ) {
 document[imgName].src = imgLocation ;
}

var preloadFlag = false;
function loadImages() {
 if (document.images) {
 left_over = newImage("center_l1.png");
 right_over = newImage("center_r1.png");
 left_over = newImage("center_l2.png");
 right_over = newImage("center_r2.png");
 left_over = newImage("center_l3.png");
 right_over = newImage("center_r3.png");
 preloadFlag = true;
 }
}


$(document).ready(function() {
	special_image = '';
});
//-->
</script>

</head>


<body bgcolor="white" text="black" onLoad="loadImages();">

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29575555-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<div align="center">


<?php 

$MAX_PAGES = 34;

$heading = "a cyclist in france";
$mainpage = true;
$left_over = "center_l1.png";
$right_over = "center_r1.png";

if (isset($_GET['page'])) {
  $current = $_GET['page'];
  if ($current >= 19) { 
	$heading = "a pilgrim in spain";
	$left_over = "center_l2.png";
	$right_over = "center_r2.png";
  }
  if ($current >= 32) { 
	$heading = "a random stickman";
	$left_over = "center_l3.png";
	$right_over = "center_r3.png";
  }
  
}
else
  $current = 0;  

if ($current == 0)
	$mainpage = true;
else
	$mainpage = false;


echo "<h1 style=\"font-family:verdana;font-size:100%\"> the (mis)adventures of $heading </h1>";
if ($mainpage) {
	echo "<h1 style=\"font-family:verdana;font-size:80%\"> (as drawn by a 5 year old child) </h1>";
	echo "<h1 style=\"font-family:verdana;font-size:70%\"> ((who, even at this young age is already showing significant signs of having a severe illustrative deficiency)) </h1>";
}
echo "<br />";

  
if ($current == 0) $comment = "";
else if ($current == 1) $comment = "of course i said no...";
else if ($current == 2) $comment = "i think this is a little like how the french see me (no frog pun intended)...";
else if ($current == 3) $comment = "its not so bad, i was downloading Michel Thomas - easy way to learn french. check out ikat though for all your internet kiosk hacking needs: http://ikat.ha.cked.net";
else if ($current == 4) $comment = "another victim of ambiguous signage...";
else if ($current == 5) $comment = "this was initially a haiku based on the form i found in an aldous huxley book i was reading at the time: --roses, the flowers are easy to paint, the leaves difficult--  after a bit of wikipedia research it turns out my poem follows neither the form or concept of a haiku. so i guess its just a poem then..";
else if ($current == 6) $comment = "ode to the wind: wind, i hate you. venhemently. passionately. i hate the way you blow randomly, chaotically. causing me to continually change my weight, my gears, my peddalling rhythm. never a chance to grow accustomed before you try another tack. i hate the way you roar in my ears, blocking out the sound of traffic approaching from behind, destroying the peace of an otherwise beautiful summer day. i hate the way you make a distance of 10km seem to stretch out to 40. challenging me psycologically with every pedal, wearing away my resolve and these old knees of mine. most of all i hate it how, just after ive stopped for a rest, you decide to calm down and all but disappear. wind, i hate you, i hate you, i hate you. fuck off and die.";
else if ($current == 7) $comment = "being french is no excuse. you should ALWAYS do some research before choosing a shop name...";
else if ($current == 8) $comment = "its the spandex that gives them the speed...";
else if ($current == 9) $comment = "further proof of the truth in my new motto: if its not completely broken, dont fix it.";
else if ($current == 10) $comment = "although near la rochelle they seemed to have a bit of a penchant for rubber gloves...";
else if ($current == 11) $comment = "renegging on my deal with the wind god... whats the worst that can happen? hes going to blow me to death?";
else if ($current == 12) $comment = "whoop! whoop! its the sound of tha police...";
else if ($current == 13) $comment = "once again the all blacks save my arse...";
else if ($current == 14) $comment = "digital information is turned into a sequence of timed waves generated by a primitve wave-machine. booster machines were required at 100m intervals to refresh the wave states...";
else if ($current == 15) $comment = "dont drink and roll...";
else if ($current == 16) $comment = "its blaaahhdy annoying...";
else if ($current == 17) $comment = "this is the 21st century and theres still people who dont speak english? baffling.";
else if ($current == 18) $comment = "suddenly biking uphill doesnt seem so hard.";

else if ($current == 19) $comment = "";
else if ($current == 20) $comment = "climbing mountains is great for perspective...";
else if ($current == 21) $comment = "tests conducted by comparing with a half full box of muslei.";
else if ($current == 22) $comment = "it could have been worse. it could have been �the song that never ends�";
else if ($current == 23) $comment = "itchy in a touchy area...";
else if ($current == 24) $comment = "ahhh, the autobus. why walk for 8 hours when you can get there by bus in 20 minutes? or am i missing the point?";
else if ($current == 25) $comment = "not really sure how this happened. i was just trying to ask if he wanted some bread...";
else if ($current == 26) $comment = "possibly the closest i will ever come to understanding why the english decided to introduce gorse into new zealand.";
else if ($current == 27) $comment = "special moral exemption for pilgrims?";
else if ($current == 28) $comment = "this turned out to be surprisingly effective - much more so than my similar experiments with a bike...";
else if ($current == 29) $comment = "but can anything truely come from nowhere? i spent far too much time pondering this question. i concluded that the triggers are just too small or too fleeting to be noticed...";
else if ($current == 30) $comment = "too many homophones ucking with my shi...";
else if ($current == 31) $comment = "nothing like burning your pants for a bit of closure. you should try it sometime.";

else if ($current == 32) $comment = "and youre fully 3D!";
else if ($current == 33) $comment = "in the 4 dimensional equivalent of the future, omnipotent overlords use chrome";
else if ($current == 34) $comment = "";

$prev = $current - 1;
$next = $current + 1;
if ($prev < 0) $prev = $MAX_PAGES;
if ($next > $MAX_PAGES) $next = 0;

$current_string = $current;
if ($current < 10) $current_string = substr($current,0,1);
else $current_string = substr($current,0,2);

echo "<div>";

echo "<a href=index.php?page=$prev 
		onMouseOver=\"change('img_center','$left_over')\"> 
		<img id=\"button_right\" name=\"button_right\" style=\"border-style:none;\" src='left.jpg' alt='previous'></a>";
echo "";
echo "<img id=\"img_center\" name=\"img_center\" style=\"border-style:none\" src='$right_over' alt='   ' />";
echo "<a href=index.php?page=$next 
		onMouseOver=\"change('img_center','$right_over')\"> 
		<img id=\"button_right\" name=\"button_right\" style=\"border-style:none\" src='right_alt.jpg' alt='next'></a>";
echo "<br />";
echo "<br />";
echo "</div>";

echo "<img id=\"img_main\" name=\"img_main\" src=\"$current_string	.png\" title='$comment' />";

?>

<script type="text/javascript">

		$("#img_main").hoverIntent({
			sensitivity: 3, // How sensitive the hoverIntent should be
			interval: 800, // How often in milliseconds the onmouseover should be checked
			over: changeSpecialImage, // Function to call when mouseover is called    
			timeout: 100 // How often in milliseconds the onmouseout should be checked
			//,out: changeSpecialImage // Function to call when mouseout is called    

		});
		
		function changeSpecialImage() {
		
			if (special_image == '')
				special_image = <?php echo $current ?> ;

			if (special_image == '34') {
				 $("#img_main").attr({ src: "34b.png" });
				 special_image = '34b';
			}
			else if (special_image == '34b') {
				 $("#img_main").attr({ src: "34c.png" });
				 special_image = '34c';
			}
			else if (special_image == '34c') {
				 window.location = "http://www.ask.com/web?q=%22i+cannot+control+my+sadistic+urge+to+massacre+innocent+2+dimensional+stick+figures.+what+are+my+options%3F%22&o=10181&l=dir&dm=all&qsrc=164&adt=0";

			}
		}

</script>

<p style="font-family:verdana;font-size:60%"><br />cheers heaps to my mate richard for hooking me up with the server space. <br />coincidentally, he happens to have a comic of his own on this very server: <a href=https://www.burntfen.com/comic/>www.burntfen.com</a><br /><br /></p>

</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16768743-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html> 


